### PR TITLE
simplifies configuration

### PR DESCRIPTION
**Pull request by schmittjoh**
This removes a few settings that had no effect anymore.

### CODE REVIEW

**Comment by philsturgeon** [comment]
What happened to these features? Isn't codesniffer still a thing on scrutinizer?

**Comment by schmittjoh** [comment]
It is. In case of code sniffer, we implicitly infer the settings from the ``checks`` configuration now. It is not necessary to explicitly configure it anymore. 

We would like to give new users a bit less options that they have to worry about as they get started. Most of the settings that are currently in this file are the defaults now (like the PSR checks for example).

**Comment by philsturgeon** [comment]
Cheers :)

**Comment by schmittjoh** [comment]
Thanks :)

**Pull request merged**
