### PR TITLE
Remove Composer self-updating from .travis.yml

### PR DESCRIPTION
**Pull request by pamil**
It is done automatically by Travis.

### CODE REVIEW

**Comment by philsturgeon** [comment]
Glad they do this now! They might have been doing it for ages, but at some point they were not. :)

**Comment by shadowhand** [comment]
Crap, moments too late... Travis currently does `composer self-update 1.0.0` which was released **2016-04-05**. The current stable version is `1.3.0`.

I recommend reverting this.

**Comment by shadowhand** [comment]
screenshot 2017-01-25 10 26 56

The biggest reason we need version 1.3.0 is because it fixes the "running composer with xdebug" problem.

**Comment by philsturgeon** [comment]
Done!

**Comment by pamil** [comment]
Travis updates Composer to 1.0.0 first and to 1.3.1 then, it's correct behaviour, isn't it?

**Comment by pamil** [comment]
There's a Sylius build running self-update on `before_script` as well, saying that the newest version is already installed: https://travis-ci.org/Sylius/Sylius/jobs/195153143#L195-L196

**Comment by shadowhand** [comment]
@pamil @philsturgeon ah crap, I messed up here. I thought the `self-update` to stable was being run because of my own `self-update` call, but looking closer I see that is **not** the case. I don't know why Travis runs `self-update 1.0.0` first, but @pamil is correct.

I recommend removing the revert command and doing a force push.

Apologies for the confusion.

**Comment by philsturgeon** [comment]
https://github.com/thephpleague/skeleton/pull/108

**Pull request merged**
