### PR TITLE
Remove composer.lock file

### PR DESCRIPTION
**Pull request by NigelGreenway**
I have removed the entry for the `composer.lock` file as it is considered good practice to commit this with the `composer.json` file as per [here](https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file).

Nigel

### CODE REVIEW

**Comment by frankdejonge** [comment]
This applies to applications, not to packages.

**Comment by frankdejonge** [comment]
[Further reading](https://philsturgeon.uk/php/2014/11/04/composer-its-almost-always-about-the-lock-file/)

**Comment by NigelGreenway** [comment]
Fair enough, never thought about it like that.

Would this be a good idea to have a wiki in this repo to explain the reason for this?

**Comment by frankdejonge** [comment]
@NigelGreenway we've got a PR lined up which tells people to look at the issues before submitting PR's. This will prevent duplicates, which this was as well. While we certainly promote the structure of this package, the decision making of excluded parts is a tricky one to tackle. We don't want to pollute this package with a never ending section about "what not to include". It can easily grow out of hand and is hard to manage in terms of "what to include and what not" in those guides. Therefor I think it's better to not take on that responsibility at all. PHP The Right Way would be a far better place for this.

**Comment by NigelGreenway** [comment]
@frankdejonge Lesson learnt. I will check PR's as well as Issues. :(

**Comment by frankdejonge** [comment]
@NigelGreenway thank you :+1: open source maintainers all over the world thank you :dancers:

**Pull request closed without merging**
