### PR TITLE
[Travis] Test lowest version dependencies

### PR DESCRIPTION
**Pull request by boekkooi**
This PR is the same #20 as but just rebased since @philsturgeon thinks it's a great idea to close PR's when there has never been any comment on them and not allow someone to update the PR (on a personal note WTF dude! do you want people to contribute or not?).

About the question why to add this please read http://evertpot.com/testing-composer-prefer-lowest/

### CODE REVIEW

**Comment by philsturgeon** [comment]
You need to calm down with that attitude, we're all still alive and it looks like you have managed to do the things I requested. 

Thanks for doing a new PR with more information.

**Comment by boekkooi** [comment]
@philsturgeon Sorry about that but I hope you do understand that having no response on a PR for 4 months and then having the PR closed with a question and a request to rebase feels like a kick in your privates. A better response would have been not to close the PR but to give me a chance to respond and answer the question and do a rebase.

The only reason why I created a new PR is because I feel very strongly about testing the lowest dependencies in a project.

**Comment by philsturgeon** [comment]
No privates were kicked. That PR needed to be better and you did that, so we're all good. We have an infinite supply of PR numbers to smash our way through.

The 4 months thing is certainly a concern. It sucks none of us League types noticed, but the skeleton repo seems to be one without a master. I'll try and get that looked into shortly.

**Comment by assertchris** [comment]
Wouldn't it make more sense to group `--prefer-source` with composer flags? Seems silly to have in both places...

**Comment by boekkooi** [comment]
I'm not sure what you mean since the `COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'` is not containing `--prefer-source` where is no duplication at the moment but adding it to `COMPOSER_FLAGS` would add duplication.

**Comment by assertchris** [comment]
I mean: should `--prefer-source` move to `COMPOSER_FLAGS` instead of having some prefers in `COMPOSER_FLAGS` and one outside of it..?

**Comment by boekkooi** [comment]
I think there are no benefits for adding `--prefer-source` to the `COMPOSER_FLAGS` because composer on travis simply works better with `--prefer-source` enabled (plus it avoids hitting the github api limit).
Also it would mean we need a global `COMPOSER_FLAGS` env variable that is set to `--prefer-source` and we would need to add `--prefer-source` to the lowest testing `COMPOSER_FLAGS` aka duplicating something we should use in any case.

**Comment by josegonzalez** [comment]
+1 merge the thing @philsturgeon. Also beers

**Comment by rosstuck** [comment]
:+1:

**Comment by philsturgeon** [comment]
Done. @josegonzalez beers are on my roof Saturday.

**Comment by boekkooi** [comment]
@philsturgeon Thanks for merging this! @josegonzalez Friday there is beer at my place (but i guess Beijing is a bit out of your range if not let me know :smile:)

**Pull request merged**
