### PR TITLE
Enhancement: Keep packages sorted

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] adds a configuration to `composer.json` which keeps packages sorted

💁 Ain't nobody got time to type 

```
$ composer require --sort-packages foo/bar
```

all the time!

h/t @hannesvdvreken

### CODE REVIEW

**Comment by frankdejonge** [comment]
@localheinz 👍

**Comment by localheinz** [comment]
Thank you, @frankdejonge!

**Comment by frankdejonge** [comment]
@localheinz all you, buddy.

**Comment by hannesvdvreken** [comment]
😛

**Pull request merged**
