### PR TITLE
Remove useless items from PR checklist

### PR DESCRIPTION
**Pull request by hansott**
These rules will be checked in the Travis build and it's already a big checklist...

### CODE REVIEW

**Comment by shadowhand** [comment]
👍

**Comment by philsturgeon** [comment]
On the fence here. You'd be amazed how many people have no idea that theres a test suite, or that they should run it. Plenty of people have no idea about CI, or that they should come back to their PR to see if its passing. 

A scary number of people - in my experience - fire and forget their PRs, and then we have to manually remind them.

Maybe we can remove these two lines, and replace with a bit of text below saying "Once your PR is created, it will trigger a build on our Continuous Integration server (link to http://www.phptherightway.com/#continuous-integration) to see if your tests and code style pass. If not, you'll need to make changes to blablabla" 

Fair? :)

**Comment by hansott** [comment]
That seems fair. Thanks for explaining! I'll make the change. 👍

**Comment by philsturgeon** [comment]
Thanks!

**Pull request merged**
