### PR TITLE
Don't ignore composer.lock

### PR DESCRIPTION
**Pull request by ravage84**
> Commit your **application's** composer.lock (along with composer.json) into version control.

https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file

> For your **library** you may commit the composer.lock file if you want to. This can help your team to always test against the same dependency versions. However, this lock file will not have any effect on other projects that depend on it. It only has an effect on the main project.

https://getcomposer.org/doc/02-libraries.md#lock-file

### CODE REVIEW

**Comment by philsturgeon** [comment]
The lock file is a 100% given for applications of course, as the documentation says, but it is optional for libraries. The docs seem to have changed as I remember it leaning more towards "dont do it" in the past, but "sometimes" is definitely accurate.

I'm on the side of "dont do it." and so this can stay in the .gitignore for me.

I wrote more on this a few months back :) 

https://philsturgeon.uk/php/2014/11/04/composer-its-almost-always-about-the-lock-file/

**Comment by ravage84** [comment]
OK, I guess that's a thing where opinions differ and I'm fine with that.

But I understand this skeleton as a compilation of PHP package development best-practices, not limited to League Packages but also relevant for the broader PHP community.

Because of this, I think such opinionated decisons should be documented somehow.
In this case a comment with a link to your blog post above the ``composer.lock`` in this file should do it.

**Comment by philsturgeon** [comment]
I get what you’re saying, really, but I still think that not letting the composer.lock sneak in there is going to cause less confusion for folks in the long run.

IMO It should be opt-in. If you know enough about why the composer.lock should be in your library, then go for it, but it should not be a default.

**Comment by ravage84** [comment]
Nope, you did get me wrong. :smile_cat: 

Even though I don't agree with you on this point, I now just want to propose this:

````
build
composer.lock # https://philsturgeon.uk/php/2014/11/04/composer-its-almost-always-about-the-lock-file/
docs
vendor
````
So people can understand **why** it is in here.
Alternatively we can link to this discussion here...

**Comment by philsturgeon** [comment]
The “League is all about Phil’s Ego” crowd are gonna fall over themselves laughing if I start jamming links to my blog in there.

Confused about how I’m getting you wrong though. I know both sides, the pros and the cons of each, and I’m making an informed decision that’s best for this project. :)

@alexbilbie @kayladns can you lot take it from here? I’ve said my bit.

**Pull request closed without merging**
