### PR TITLE
Update CONDUCT.md to 1.3.0

### PR DESCRIPTION
**Pull request by bcrowe**

### CODE REVIEW

**Comment by frankdejonge** [comment]
We'll have to look if our amendments are still in place.

**Comment by frankdejonge** [comment]
It looks like our amendment has fallen between the cracks.

**Comment by bcrowe** [comment]
This: https://github.com/thephpleague/skeleton/commit/da9476b4eb9622a40f6dcf8eafc2eda517044ef9 ?

**Comment by philsturgeon** [comment]
Hey @bcrowe! Sorry this got dropped. Would you be so excellent as to update to their latest? 

http://contributor-covenant.org/version/1/4/

Seeing as it has this in the scope, I don't think we need our amendments in place anymore. 

> Scope

> This Code of Conduct applies both within project spaces and in public spaces when an individual is representing the project or its community. Examples of representing a project or community include using an official project e-mail address, posting via an official social media account, or acting as an appointed representative at an online or offline event. Representation of a project may be further defined and clarified by project maintainers.

IMO, CC is nowhere near as scary (to those who were ever scared of it) as it was before.

**Comment by philsturgeon** [comment]
Did it myself, @bcrowe you lazy f**k. <3

**Comment by bcrowe** [comment]
@philsturgeon Oh hey, thanks buddy! 💋

**Pull request closed without merging**
