### PR TITLE
Added phpcs as a dependency, added a composer sniff command

### PR DESCRIPTION
**Pull request by hassankhan**
As requested in #23

### CODE REVIEW

**Comment by ravage84** [comment]
@hassankhan how about https://github.com/thephpleague/skeleton/pull/41 ?

**Comment by hassankhan** [comment]
Either way, as long as it's in. I'd made a huge PR to this repo in the past, and had to break it down into smaller PRs. This is one of them :)

**Comment by theofidry** [comment]
If there's a StyleCI config file why including PHPCS as well?

**Comment by colinodell** [comment]
You can run PHPCS locally to identify and fix some issues before pushing code to Github.

**Comment by theofidry** [comment]
But what's the point to add a new dependency to your project if you setup a service like StyleCI that can fix it anyway?

Besides as it's a static tool (it doesn't execute your code), it could be used as a bin instead to avoid polluting your libraries dependencies with it.

**Comment by colinodell** [comment]
> But what's the point to add a new dependency to your project if you setup a service like StyleCI that can fix it anyway?

For the same reason you run phpunit tests locally instead of relying on TravisCI results - you're able to identify and resolve issues earlier in the development process.

Because it's a dev dependency, it will **only** be installed for people actively developing the library.

For example, if you're building a Laravel application that includes a League project, PHPCS will not be installed or become a dependency of your Laravel app.

**Comment by theofidry** [comment]
>Because it's a dev dependency, it will only be installed for people actively developing the library.

That explains your views on the first point and this is where we disagree: it's not a dev dependency, it's a dedicated app that you decided to use for your project. This is precisely why tools like https://github.com/sensiolabs-de/deptrac are not recommending an install via Composer (IIRC you can't even use it if you do so).

The same could be said about PHPUnit but there is a big difference with PHPUnit: you are using PHPUnit code in your code base AND it *executes* your code. Using a PHAR for it can be dangerous. For example if the PHPUnit PHAR is bundled with `symfony/yaml 3.1` and your library is using `symfony/yaml 2.8` running the tests with the PHAR might not work: it can throw an error, silently fail or give weird bugs.

**Comment by philsturgeon** [comment]
Locally might fail and the Travis (not using a phar) would error. Yay for checking thing s twice.

What is the concern here? Code style is not as fundamental as tests passing or failing, so that example doesn't seem entirely relevant to this chat.

--
Phil Sturgeon

**Comment by theofidry** [comment]
@philsturgeon to be honest my point is not so much about checking the code style or not, but about installing a dedicate app as a dev dependency which corrupts your project dependencies for not reason. If you want to include it, there is plugins like https://github.com/bamarni/composer-bin-plugin to do it or people just use PHARs or global installed binaries for it.

I'm am talking of PHPCSSniffer here, but it could have been PHPCSFixer or it is `scrutinizer/ocular` (why would you install that as a dev package? It doesn't even take two seconds to download on Travis and it's the only place where you ever use it).

**Comment by philsturgeon** [comment]
I definitely see your point. I think our definitions of dedicated app vary a bit when it comes to dev requirements, but pushing people towards hosted sass solutions is certainly something we have agonised over.

Pushing people towards one service or another is never ideal, but the idea here is to 

A) avoid us having to set up unique snowflakes for each package WE make (or bring onboard)

B) highlight the importance of such services to others who wish to use our skeleton package as a base for their own.

When it comes to such tools messing with your own dependencies, well, that won't happen. If YOUR app wants symfony/yaml 2.8 and phpcs wants 3.1, that's entirely fine. The dev dependencies don't go anywhere near your app dependencies so you can absolutely have both. They sit in entirely different places and one will never effect the other.

If two dev dependencies want two different versions of the same thing, composer will either reconcile that or you have a standard decency hell issue, which is normally resolved by bumping the versions of those dev dependencies. This assumes they're being actively maintained of course, but if they become stale we'd not use them anymore. 

Does that alleviate any of your concerns, or am I missing your point?

--
Phil Sturgeon

**Comment by theofidry** [comment]
>Pushing people towards one service or another is never ideal

I'm not really leaning toward pushing people to use StyleCI, but that's how I interpreted the presence of the `styleci.yml` in the skeleton.

>When it comes to such tools messing with your own dependencies, well, that won't happen. If YOUR app wants symfony/yaml 2.8 and phpcs wants 3.1, that's entirely fine. The dev dependencies don't go anywhere near your app dependencies so you can absolutely have both. They sit in entirely different places and one will never effect the other.

I'm not sure to follow: if the app is installed via Composer as a dev dependency, you run into a problem straight away. If you're using a PHAR, it's fine as long as the tool used doesn't execute the code (which is the case with phpcs).

>This assumes they're being actively maintained of course, but if they become stale we'd not use them anymore.

This is a big assumption 😆 Sometimes you're not ready to commit to maintain your own version and you still need this tool.

>Does that alleviate any of your concerns, or am I missing your point?

In the past I struggled with this as I was using several dedicated app but:

- I couldn't install them together via Composer (dev conflicts, notably with `nikic/parser`, hard to upgrade and common in static analysis tools)
- I wasn't satisfied with PHARs: you can't keep track of them in git unless you are ready to commit them which have a non negligible impact.

In the end I commited the PHARs as it was a company thing and we were fine with a bit of a performance impact when cloning the code, but it's not really viable for open source libraries.

However now there is tools like https://github.com/bamarni/composer-bin-plugin that can address those problems. If we take the example of PHPCS Sniffer and Scrutinizer Ocular is:

```
composer require bamarni/composer-bin-plugin
composer bin scrutinizer require scrutinizer/ocular
composer bin codecs squizlabs/php_codesniffer
```

And then you can access to `vendor/bin/ocular` and `vendor/bin/php_codesniffer` as before without having your library polluted by guzzle, JMS Serializer, Symfony Console and Process...

But it's alright to disagree on this and let's be honest nobody cares (unless you are a bit of a maniac like me) before it does become a problem. But as there is simple solutions to solve this problem, I wish those solution were used instead :)

**Comment by philsturgeon** [comment]
I'm on mobile so can't do quotes.

It's not about agreeing or disagreeing, I was just trying to get to the bottom of your concerns. 

We're talking about a few things which is tough to separate. 

1.) As I said we're not pushing people to specific services intentionally, we just want to highlight that these services in general are important and useful. The only alternative to having one, would be having shitloads, and I'm not into that.

2.) Assuming phpcs and phpunit remain actively maintained is not a massive assumption by any means, they've been that way for a decade. 

3.) As for the dev dependency problem, I'm really not sure what problem you're getting at. Dev dependencies of a component, and the dependencies of an application that somebody installs a component into will never conflict. They're totally different vendor folders. We agree and understand that, right? 

The worst that can happen by relying on phpcs/phpunit/etc as dev dependencies is that the dev dependencies _of components_ will potentially cause a conflict if not updated to support a new major version. This is how dependencies work, and composer is built to handle that. If A requires B and a new B comes out, you either get a new A or keep the old B for a while. 

Seeing as they're actively developed and yet with relatively stable APIs, dependency hell is rare and in years of using composer has never happened to me for dev dependencies. 

Again, interested to hear how it is a problem, but from your explanations so far I'm not at all concerned. 

Regardless of my understanding of your specific worries, I personally don't ever want to see phar's committed to repos for stuff like phpunit or something as simple as phpcs. Maybe composer could be used to download the remote file and shove it in place, but shoving all that in your repo just for some dev dependencies is just extra work for no noticeable gain!

--
Phil Sturgeon

**Comment by theofidry** [comment]
>1.) As I said we're not pushing people to specific services intentionally, we just want to highlight that these services in general are important and useful. The only alternative to having one, would be having shitloads, and I'm not into that.

Perfectly fair. I don't have a strong opinion on this so I won't try to overstep my bonds to push for something here. Having a skeleton ready for box phpcs and styleci or make a choice on which one to choose is more a matter for you to choose. The topic I'm debating is rather after the next point.

>Regardless of my understanding of your specific worries, I personally don't ever want to see phar's committed to repos for stuff like phpunit or something as simple as phpcs. Maybe composer could be used to download the remote file and shove it in place, but shoving all that in your repo just for some dev dependencies is just extra work for no noticeable gain!

Oh I by no means am pushing for that (committing a PHAR). I apologize for the bad phrasing if that's how you understood it, I simply said I picked that solution at that time to be pragmatic and we didn't have time to really address the issue. I'm not recommending it either and I dare say I'm strongly against it in any open source library. I think phpunit belongs to the dev dependencies. But for phpcs or scrutinizer/ocular, they don't IMO (for the reasons explained on the next point).

3.) As for the dev dependency problem, I'm really not sure what problem you're getting at. Dev dependencies of a component, and the dependencies of an application that somebody installs a component into will never conflict. They're totally different vendor folders. We agree and understand that, right?

I agree on what you said but I'm not talking of the consumer of the package, but on the maintainer (or any contributor).

Just for the sake of clarity, by "app", in the current context of managing a library, I mean of a tool such as phpcs, `scrutinizer/ocular`, `sensiolabs-de/deptrac`, `phpmetrics/PhpMetrics` etc, i.e. tools used for your project housekeeping but not required to use your library or to run your tests but only for a maintainer or contributor. Now you might have another more suited term for it, but I'll use this one or "tool" meanwhile 'coz I need to call it something.

The way you install this kind of tool has a big impact on your libraries. For example, if you go for the simple way of having everything as a dev dependency in your `composer.json`, you might, very easily not be able to do so because of dependencies conflict. You could stop at that and say the app X should update its dependencies, but to me the problem is deeper: those tools have their own dependencies in order to run and they don't execute your code, I see no reason to mix this app dependencies with the one of your library (which is what you are doing by putting them in your dev dep). And I can see 3 scenario from doing this:

1) Best scenario you don't face a problem dep conflict (\o/). Keep your carefree life and don't question anything because everything just works.

2) A less good scenario that already caught me by surprise: because installing tool X influence the way your dep are resolved with Composer. Even if you put a `--prefer-lower` option in Composer, you may not have the same result as the end consumer, hence failing to test that scenario. A dev tool such as phpunit may suffice to cause this issue and I have no real solution here, only reducing the dev dep to the strict minimum to avoid as much as possible this situation.

3) The third case, you get a dep conflict right away in which case you:

- A) drop the idea of having this tool
- B) contribute to make it compatible
- C) use an alternative solution like I'll suggest in a min

So in the peculiar case of this PR, I doubt it cause any big issue for most people as phpcs has almost no dep (I'm a bit less sure about scritinizer/ocular, having a `~3.0` constrain on `guzzle/guzzle` could be).

But let's remember we are talking of a *skeleton*, which people will use as a base and look up as a model. Which is why I would advocate an alternative solution as bamarni/composer-bin-plugin (there other similar Composer plugins, I picked this one because it's the one I'm familiar with and I didn't feel the need to try all of them).

On a side note: sorry if this became such a lengthy discussion, I definitely didn't expect it so I appreciate that you're taking the time to reply and try to understand my concerns

**Comment by philsturgeon** [comment]
I see what you're getting at now. Thanks for explaining things. 

Let's use these terms.

- library: your composer package
- app: some application being built by a consumer of your librry. 
- tool: phpcs and stuff like that

Back to it: I'm not at all familiar with ocular and have not looked at the requirements, doing so would flavour the conversation rather differently. 

The fact that they're [committing their lock file](https://philsturgeon.uk/php/2014/11/04/composer-its-almost-always-about-the-lock-file/) for a component is something I'm personally against, as it pegs the requirements much too tightly. I'm in the "take any minor above the one I built it on and I'll hope they stick to SemVer" camp myself. 

Now, ocular using a bloody old version of Guzzle and being very specific about which it wants looks terrible to me, so I'd be all for removing ocular from the skeleton. 

That is a very different matter to PHPCS, which this PR is proposing. 

PHPCS as you say has no deps and only one dev dep: PHPUnit. 

PHPUnit has mostly dependencies built by the same the author himself, and a few like this: `"symfony/yaml": "~2.1|~3.0",` that's a pretty wide set of dependencies, literally anything in the 2.1 to 3.0 range, and it's not like they're smacking out new YAML versions on a monthly basis. 

Due to this, I don't share your concerns for the more mature, stable, and well established packages, and 👍 this PR. 

But, after your comments, I would suggest to folks that we remove ocular.

Seem fair?

**Comment by philsturgeon** [comment]
@hassankhan conflicts :)

**Comment by theofidry** [comment]
I would love the skeleton to promote a bit more best practices even if it means over-engineering a bit but let's be pragmatic, 👍 for phpcs, and for ocular I would recommend to download the phar on Travis when required (it doesn't even take 2sec, surely nobody minds that)

**Comment by hassankhan** [comment]
Sorry, I don't keep up with PHP much these days, could someone else please take over?

**Comment by TomasVotruba** [comment]
@theofidry Agree with both!

**Comment by philsturgeon** [comment]
Taking care of this over in #41 which does the same thing.

**Pull request closed without merging**
